import {
  Service,
  TeamMember,
  Project,
  ProcessStep,
  Testimonial,
} from "./types";

export const SERVICES: Service[] = [
  {
    id: "1",
    title: "Custom Web Apps",
    description:
      "Scalable, high-performance React applications tailored to your business needs.",
    icon: "Globe",
    tools: [
      "React",
      "Next.js",
      "TypeScript",
      "Tailwind",
      "Boostrap",
      "Angular",
    ],
  },
  {
    id: "2",
    title: "Cloud Infrastructure",
    description:
      "Robust cloud environments with serverless architecture for global scalability.",
    icon: "Cloud",
    tools: ["AWS", "Docker", "Kubernetes", "CI/CD"],
  },
  {
    id: "3",
    title: "Backend Systems",
    description:
      "Secure and maintainable APIs built with modern frameworks and databases.",
    icon: "Server",
    tools: [
      "Node.js",
      "PostgreSQL",
      "Python",
      "Redis",
      "MongoDB",
      "AWS Lambda",
    ],
  },
  {
    id: "4",
    title: "UI/UX Design",
    description:
      "User-centered interface and experience design that creates intuitive, engaging, and visually appealing digital products.",
    icon: "Palette",
    tools: ["Figma", "Adobe XD", "Framer", "Design Systems"],
  },
  {
    id: "5",
    title: "Mobile App Development",
    description:
      "Cross-platform mobile applications built with ract native, Flutter and Supabase for real-time data synchronization and performance.",
    icon: "Smartphone",
    tools: ["Flutter", "Dart", "Supabase", "socket.io", "React Native"],
  },
  {
    id: "6",
    title: "video editing",
    description:
      "Video editing service for creating engaging and professional videos tailored to your business needs.",
    icon: "Video",
    tools: ["Adobe Premiere Pro", "Adobe After Effects", "Final Cut Pro", "DaVinci Resolve"],
  },
];

export const TEAM: TeamMember[] = [
  {
    id: "1",
    name: "Naveen Saini",
    role: "Full Stack Developer",
    image: "./images/naveen.JPG",
    skills: [
      "System Design",
      "React.js",
      "Tailwind CSS",
      "AWS",
      "TypeScript",
      "Next.js",
      "Node.js",
      "Gemini AI",
      "Dynamic API",
      "Angular",
      "HTML5",
      "Bootstrap",
      "CSS3",
      "JavaScript",
      "MongoDB",
      "PostgreSQL",
      "wordpress",
    ],
    socials: {
      github: "https://github.com/",
      linkedin: "https://www.linkedin.com/in/naveen-saini-78201a293/",
      LiveDemo: "https://naveen.whatwebuildnext.com/",
    },
  },
  {
    id: "2",
    name: "Ayush Singh Chouhan",
    role: "Frontend and Backend Specialist",
    image: "./images/ayush1.png",
    skills: [
      "System Design",
      "React.js",
      "Tailwind CSS",
      "AWS",
      "TypeScript",
      "Next.js",
      "Node.js",
      "Angular",
      "MVC",
      "HTML",
      "Bootstrap",
      "CSS",
      "JavaScript",
      "MongoDB",
      "PostgreSQL",
      "python",
      "microservices",
      "docker",
    ],
    socials: {
      github: "https://github.com/Jeratos",
      linkedin: "https://www.linkedin.com/in/ayush-chouhan-31a064222/",
      LiveDemo: "https://ayush.whatwebuildnext.com/",
    },
  }, 
  {
    id: "3",
    name: "Barinder Singh",
    role: "DevOps Engineer",
    image: "./images/barindar.jpeg",
    skills: [
      "System Design",
      "React.js",
      "Tailwind CSS",
      "AWS",
      "TypeScript",
      "Next.js",
      "Node.js API",
      "React",
      "Node.js",
      "Gemini AI",
      "Dynamic API",
      "Angular",
      "MVC",
      "HTML5",
      "Bootstrap",
      "CSS3",
      "JavaScript",
      "MongoDB",
      "wordpress",
      "python",
      "docker",
    ],
    socials: {
      github: "https://github.com/",
      linkedin: "https://www.linkedin.com/in/naveen-saini-78201a293/",
      LiveDemo: "https://my-portfolio-azure-omega-11.vercel.app/",
    },
  },
  {
    id: "4",
    name: "Arijit Mondal",
    role: "Full-Stack Developer",
    image: "./images/arijit.jpg",
    skills: [
      "System Design",
      "AWS",
      "React.js",
      "Next.js",
      "JavaScript",
      "TypeScript",
      "Node.js",
      "Express.js",
      "HTML",
      "CSS",
      "Bootstrap",
      "Tailwind CSS",
      "MongoDB",
      "SQL",
      "python",
      "docker",
    ],
    socials: {
      github: "https://github.com/Arijit-mondal099",
      linkedin: "https://www.linkedin.com/in/arijit-mondal-211217287",
      LiveDemo: "https://arijitmondal.vercel.app/",
    },
  },
  {
    id: "5",
    name: "Kamran Hashmi",
    role: "App Developer",
    image: "./images/kamran.jpeg",
    skills: [
      "System Design",
      "Tailwind CSS",
      "Supabase",
      "AWS",
      "Flutter",
      "dart",
      "Node.js",
      "Gemini AI",
      "Dynamic API",
      "MVC",
      "HTML5",
      "Bootstrap",
      "CSS3",
      "JavaScript",
      "MongoDB",
      "postgreSQL",
    ],
    socials: {
      github: "https://github.com/K-hashmi9065",
      linkedin: "https://www.linkedin.com/in/k-hashmi9065/",
      LiveDemo: "https://kamran-portfolio-gilt.vercel.app/",
    },
  },
  {
    id: "6",
    name: "Alok Raj ",
    role: "Cloud Architect",
    image: "./images/alok.jpeg",
    skills: [
      "System Design",
      "React.js",
      "Tailwind CSS",
      "AWS",
      "TypeScript",
      "Next.js",
      "Node.js API",
      "React",
      "Node.js",
      "Gemini AI",
      "Dynamic API",
      "Angular",
      "MVC",
      "HTML5",
      "Bootstrap",
      "CSS3", 
      "JavaScript",
      "MongoDB",
      "wordpress",
      "python",
      "docker",
    ],
    socials: {
      github: "https://github.com/raj45alok",
      linkedin: "https://www.linkedin.com/in/alokraj54/",
      LiveDemo: "https://my-portfolio-azure-omega-11.vercel.app/",
    },
  },

  {
    id: "7",
    name: "Mohammad Parwez",
    role: "Full Stack Developer",
    image: "./images/pawez.jpeg",
    skills: [
      "System Design",
      "React.js",
      "Tailwind CSS",
      "AWS",
      "TypeScript",
      "Next.js",
      "Node.js API",
      "React",
      "Node.js",
      "Gemini AI",
      "Dynamic API",
      "Angular",
      "MVC",
      "HTML5",
      "Bootstrap",
      "CSS3", 
      "JavaScript",
      "MongoDB",
      "wordpress",
      "python",
      "docker",
    ],
    socials: {
      github: "https://github.com/Mohammad-Parwez",
      linkedin: "https://www.linkedin.com/in/mohammad-parwez-47b972247",
      LiveDemo: "https://portfolio-ten-lilac-avdvtc47yu.vercel.app/",
    },
  }, 
  {
    id: "8",
    name: "Kaif Reza",
    role: "Video Editor",
    image: "./images/kaif.jpeg",
    skills: [
      "Video Editing",
      "Adobe Premiere Pro",
      "Adobe Photoshop",
      "CapCut Editing",
      "Canva Design",
      "AI Video Editing Tools",
      "AI Voice / Voiceover Tools",
      "Short-form Content Editing",
      "Color Correction & Color Grading", 
      "Transitions & Effects",
      "Audio Editing & Sync",
      "Storytelling & Content Structuring",
      "Social Media Content Creation",
      "Fast Delivery & Client Handling"
    ],
    socials: {
      github: "",
      linkedin: "",
      LiveDemo: "",
    },
  }, 
];

export const PROJECTS: Project[] = [
  {
    id: "1",
    title: "DroneTv",
    category: "Developed a full-featured web platform that allows businesses in the drone industry to list their companies, professionals, and events. Full-Stack AI Powered SAAS Application.",
    image: "./images/dronetv.png",
    tags: ["React", "Typescript", "OpenAI", "Tailwind CSS", "AWS"],
    github: "https://github.com/gisipageums-droid/Dronetv/tree/main",
    liveUrl: "https://www.dronetv.in",
  },
  {
    id: "2",
    title: "Health",
    category: "Full-Stack Doctor appointment booking application. Aim to bridge the gap between patients and healthcare providers, making it easier for you to access the care you need, when you need it.",
    image: "./images/health.png",
    tags: ["React.js", "Node.js", "Express.js", "MongoDB"],
    github: "https://github.com/Arijit-mondal099/health",
    liveUrl: "https://health-frontend-c4x4.onrender.com/",
  },
  {
    id: "3",
    title: "PhishFarm",
    category: "Diagnosed and resolved critical bugs in the production environment, optimized application performance, and successfully managed end-to-end project deployment workflows.",
    image: "./images/PhishFarm.jpeg",
    tags: ["React.js", "Node.js", "Express.js", "MongoDB","typescript","tailwind css"],
    github: "#",
    liveUrl: "https://www.phishfarm.com",
  },
  {
    id: "4",
    title: "ETS (Employee Tracking System)",
    category: "A SaaS platform developed at iPageums to track employee activity, attendance, and project statuses. Includes a real-time chat section for colleagues.",
    image: "./images/ETS.png",
    tags: ["React.js", "Node.js", "Express.js", "MongoDB","AWS","typescript","tailwind css"],
    github: "#",
    liveUrl: "https://ipageets.vercel.app/",
  },
  {
    id: "5",
    title: "aiyuh app",
    category: "Aiyuh is a health tracking mobile application built using Flutter and Supabase that monitors user health metrics and provides personalized diet recommendations based on real-time data and user inputs.",
    image: "./images/aiyuh.jpeg",
    tags: ["Flutter", "Dart", "Supabase", "postgreSQL", "socket.io"],
    github: "#",
    liveUrl: "https://play.google.com/store/apps/details?id=com.aiyuh.user&pcampaignid=web_share",
  },
  {
    id: "6",
    title: "PaisaBchao (price comparison website)",
    category: "The ultimate price comparison platform for smart shoppers in India. We scan thousands of products across all major platforms to find you the best value.",
    image: "./images/paisabchao.png",
    tags: ["Next.js", "Node.js", "Express.js", "PostgreSQL","openai","socket.io","typescript","tailwind css"],
    github: "#",
    liveUrl: "https://www.paisabchao.com/",
  }
];

export const PROCESS: ProcessStep[] = [
  {
    id: "1",
    title: "Discovery",
    description:
      "We dive deep into your requirements and business goals to map out a technical blueprint.",
    icon: "Search",
  },
  {
    id: "2",
    title: "Design & Prototype",
    description:
      "Iterative design phases focusing on high-fidelity user experiences and architecture.",
    icon: "Figma",
  },
  {
    id: "3",
    title: "Agile Development",
    description:
      "Continuous integration and deployment cycles with regular feedback loops.",
    icon: "Code",
  },
  {
    id: "4",
    title: "Scale & Deploy",
    description:
      "Automated testing and cloud deployment ensuring 99.9% uptime and global reach.",
    icon: "Rocket",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "1",
    name: "James Wilson",
    role: "CTO",
    company: "FinTech Hub",
    content:
      "What we build next transformed our legacy platform into a high-speed React dashboard in record time. Their attention to technical detail is unmatched.",
    avatar: "./images/default_avatar.png",
  },
  {
    id: "2",
    name: "Lila Rodriguez",
    role: "Product Owner",
    company: "EcoStream",
    content:
      "The web app they built using React/next handles massive traffic flawlessly. Engineering at its finest.",
    avatar: "./images/default_avatar.png",
  },
  {
    id: "3",
    name: "Pritam Kumar",
    role: "Founder",
    company: "Healthhepta",
    content:
      "Building a scalable healthcare platform was smooth and reliable thanks to the secure, high-performance system what we build next delivered. It helped us serve patients efficiently while maintaining data privacy and trust.",
    avatar: "./images/default_avatar.png",
  },
];

export const TECH_STACK = [
  // Frontend
  "HTML",
  "CSS",
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Redux",
  "Tailwind CSS",
  "Bootstrap",

  // Backend
  "Node.js",
  "Express.js",
  "Python",
  "Django",
  "FastAPI",

  // Databases
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "Firebase",
  "Redis",

  // DevOps & Cloud
  "Docker",
  "Kubernetes",
  "AWS",
  "AWS S3",
  "AWS Lambda",
  "Nginx",
  "PM2",

  // Tools & Platforms
  "Git",
  "GitHub",
  "Postman",
  "Figma",
  "Canva",

  // CMS & Others
  "WordPress",
  "SEO",
  "Razorpay",
  "JWT Authentication",
];
