import {
  Service,
  TeamMember,
  Project,
  ProcessStep,
  Testimonial,
} from "./types";

export const SERVICES: Service[] = [
  {
    id: "1",
    title: "Custom Web Apps",
    description:
      "Scalable, high-performance React applications tailored to your business needs.",
    icon: "Globe",
    tools: [
      "React",
      "Next.js",
      "TypeScript",
      "Tailwind",
      "Boostrap",
      "Angular",
    ],
  },
  {
    id: "2",
    title: "Cloud Infrastructure",
    description:
      "Robust cloud environments with serverless architecture for global scalability.",
    icon: "Cloud",
    tools: ["AWS", "Docker", "Kubernetes", "CI/CD"],
  },
  {
    id: "3",
    title: "Backend Systems",
    description:
      "Secure and maintainable APIs built with modern frameworks and databases.",
    icon: "Server",
    tools: [
      "Node.js",
      "PostgreSQL",
      "Python",
      "Redis",
      "MongoDB",
      "AWS Lambda",
    ],
  },
  {
    id: "4",
    title: "UI/UX Design",
    description:
      "User-centered interface and experience design that creates intuitive, engaging, and visually appealing digital products.",
    icon: "Palette",
    tools: ["Figma", "Adobe XD", "Framer", "Design Systems"],
  },
];

export const TEAM: TeamMember[] = [
  {
    id: "1",
    name: "Naveen Saini",
    role: "Full Stack Developer",
    image: "https://picsum.photos/seed/alex/400/400",
    skills: [
      "System Design",
      "React.js",
      "Tailwind CSS",
      "AWS",
      "TypeScript",
      "Next.js",
      "Node.js API",
      "React",
      "Node.js",
      "Gemini AI",
      "Dynamic API",
      "Angular",
      "MVC",
      "HTML5",
      "Bootstrap",
      "CSS3",
      "JavaScript",
      "MongoDB",
      "wordpress",
      "python",
      "docker",
    ],
    socials: {
      github: "https://github.com/",
      linkedin: "https://www.linkedin.com/in/naveen-saini-78201a293/",
      LiveDemo: "https://my-portfolio-azure-omega-11.vercel.app/",
    },
  },
  {
    id: "2",
    name: "Ayush Singh Chohan",
    role: "Frontend and Backend Specialist",
    image: "./images/ayush.jpeg",
    skills: [
      "System Design",
      "React.js",
      "Tailwind CSS",
      "AWS",
      "TypeScript",
      "Next.js",
      "Node.js",
      "Angular",
      "MVC",
      "HTML",
      "Bootstrap",
      "CSS",
      "JavaScript",
      "MongoDB",
      "python",
      "docker",
    ],
    socials: {
      github: "https://github.com/Jeratos",
      linkedin: "https://www.linkedin.com/in/ayush-chouhan-31a064222/",
      LiveDemo: "www.kalling.site",
    },
  },
  {
    id: "3",
    name: "Barinder Singh",
    role: "DevOps Engineer",
    image: "https://picsum.photos/seed/marcus/400/400",
    skills: [
      "System Design",
      "React.js",
      "Tailwind CSS",
      "AWS",
      "TypeScript",
      "Next.js",
      "Node.js API",
      "React",
      "Node.js",
      "Gemini AI",
      "Dynamic API",
      "Angular",
      "MVC",
      "HTML5",
      "Bootstrap",
      "CSS3",
      "JavaScript",
      "MongoDB",
      "wordpress",
      "python",
      "docker",
    ],
    socials: {
      github: "https://github.com/",
      linkedin: "https://www.linkedin.com/in/naveen-saini-78201a293/",
      LiveDemo: "https://my-portfolio-azure-omega-11.vercel.app/",
    },
  },
  {
    id: "4",
    name: "Arijit Mondal",
    role: "Full-Stack Developer",
    image: "./images/arijit.jpg",
    skills: [
      "System Design",
      "AWS",
      "React.js",
      "Next.js",
      "JavaScript",
      "TypeScript",
      "Node.js",
      "Express.js",
      "HTML",
      "CSS",
      "Bootstrap",
      "Tailwind CSS",
      "MongoDB",
      "SQL",
      "python",
      "docker",
    ],
    socials: {
      github: "https://github.com/Arijit-mondal099",
      linkedin: "https://www.linkedin.com/in/arijit-mondal-211217287",
      LiveDemo: "https://arijitmondal.vercel.app/",
    },
  },
  {
    id: "5",
    name: "Vikas Rana",
    role: "Product Designer",
    image: "https://picsum.photos/seed/jordan/400/400",
    skills: [
      "System Design",
      "React.js",
      "Tailwind CSS",
      "AWS",
      "TypeScript",
      "Next.js",
      "Node.js API",
      "React",
      "Node.js",
      "Gemini AI",
      "Dynamic API",
      "Angular",
      "MVC",
      "HTML5",
      "Bootstrap",
      "CSS3",
      "JavaScript",
      "MongoDB",
      "wordpress",
      "python",
      "docker",
    ],
    socials: {
      github: "https://github.com/",
      linkedin: "https://www.linkedin.com/in/naveen-saini-78201a293/",
      LiveDemo: "https://my-portfolio-azure-omega-11.vercel.app/",
    },
  },
  {
    id: "6",
    name: "Alok Raj ",
    role: "QA Automation",
    image: "https://picsum.photos/seed/riley/400/400",
    skills: [
      "System Design",
      "React.js",
      "Tailwind CSS",
      "AWS",
      "TypeScript",
      "Next.js",
      "Node.js API",
      "React",
      "Node.js",
      "Gemini AI",
      "Dynamic API",
      "Angular",
      "MVC",
      "HTML5",
      "Bootstrap",
      "CSS3",
      "JavaScript",
      "MongoDB",
      "wordpress",
      "python",
      "docker",
    ],
    socials: {
      github: "https://github.com/",
      linkedin: "https://www.linkedin.com/in/naveen-saini-78201a293/",
      LiveDemo: "https://my-portfolio-azure-omega-11.vercel.app/",
    },
  },
];

export const PROJECTS: Project[] = [
  {
    id: "1",
    title: "DroneTv",
    category: "Full-Stack AI Powered SAAS Application.",
    image: "./images/dronetv.png",
    tags: ["React", "Typescript", "OpenAI", "Tailwind CSS", "AWS"],
    github: "https://github.com/gisipageums-droid/Dronetv/tree/main",
    liveUrl: "www.dronetv.in",
  },
  {
    id: "2",
    title: "Health",
    category: "Full-Stack Doctor appointment booking application.",
    image: "./images/health.png",
    tags: ["React.js", "Node.js", "Express.js", "MongoDB"],
    github: "https://github.com/Arijit-mondal099/health",
    liveUrl: "https://health-frontend-c4x4.onrender.com/",
  },
];

export const PROCESS: ProcessStep[] = [
  {
    id: "1",
    title: "Discovery",
    description:
      "We dive deep into your requirements and business goals to map out a technical blueprint.",
    icon: "Search",
  },
  {
    id: "2",
    title: "Design & Prototype",
    description:
      "Iterative design phases focusing on high-fidelity user experiences and architecture.",
    icon: "Figma",
  },
  {
    id: "3",
    title: "Agile Development",
    description:
      "Continuous integration and deployment cycles with regular feedback loops.",
    icon: "Code",
  },
  {
    id: "4",
    title: "Scale & Deploy",
    description:
      "Automated testing and cloud deployment ensuring 99.9% uptime and global reach.",
    icon: "Rocket",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "1",
    name: "James Wilson",
    role: "CTO",
    company: "FinTech Hub",
    content:
      "What we build next transformed our legacy platform into a high-speed React dashboard in record time. Their attention to technical detail is unmatched.",
    avatar: "./images/default_avatar.png",
  },
  {
    id: "2",
    name: "Lila Rodriguez",
    role: "Product Owner",
    company: "EcoStream",
    content:
      "The web app they built using React/next handles massive traffic flawlessly. Engineering at its finest.",
    avatar: "./images/default_avatar.png",
  },
  {
    id: "3",
    name: "Pritam Kumar",
    role: "Founder",
    company: "Healthhepta",
    content:
      "Building a scalable healthcare platform was smooth and reliable thanks to the secure, high-performance system what we build next delivered. It helped us serve patients efficiently while maintaining data privacy and trust.",
    avatar: "./images/default_avatar.png",
  },
];

export const TECH_STACK = [
  // Frontend
  "HTML",
  "CSS",
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Redux",
  "Tailwind CSS",
  "Bootstrap",

  // Backend
  "Node.js",
  "Express.js",
  "Python",
  "Django",
  "FastAPI",

  // Databases
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "Firebase",
  "Redis",

  // DevOps & Cloud
  "Docker",
  "Kubernetes",
  "AWS",
  "AWS S3",
  "AWS Lambda",
  "Nginx",
  "PM2",

  // Tools & Platforms
  "Git",
  "GitHub",
  "Postman",
  "Figma",
  "Canva",

  // CMS & Others
  "WordPress",
  "SEO",
  "Razorpay",
  "JWT Authentication",
];
